name: Create Release Windows Only

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-binutils
          update: true

      - name: Compile Windows Version
        shell: msys2 {0}
        run: |
          windres resource.rc -o resource.o
          g++ -O3 main-2.cpp resource.o -o Mandelbrot-2.exe \
          -lgdi32 -luser32 -ldwmapi -fopenmp -static -mwindows \
          -D__USE_MINGW_ANSI_STDIO=1
          strip Mandelbrot-2.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Mandelbrot set. 32-bit. 60 FPS. 80-bit. OpenMP. Supersampling 2x2. Color rotation ${{ github.ref_name }}"
          body: |
            ## Mandelbrot set. 32-bit. 60 FPS. 80-bit. OpenMP. Supersampling 2x2. Color rotation 
            <video src="https://github.com/user-attachments/assets/77f35c8b-98df-4b2b-ba09-b887dfff9f89" controls width="800"></video>
            <video src="https://github.com/user-attachments/assets/3ae964ac-2fa4-4283-8bc3-9167dedc3005" controls width="800"></video>
            <video src="https://github.com/user-attachments/assets/990baae9-3eeb-4eea-adec-c06d4f0741f4" controls width="800"></video>
            - True 32-bit BGRA
            - Synchronization with DwmFlush
            - High-Precision Rendering (80-bit)
            - Multi-threaded performance (OpenMP)
            - True SSAA 2x2 (4 independent samples per pixel) direct RGB-space integration
            - The Red, Green, and Blue channels are calculated using sine and cosine waves
          files: Mandelbrot-2.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PAT }}
